### PR TITLE
apply t/04_leak.t hang patch from Zefram RT #81860

### PR DESCRIPTION
**Pull request by leejo**
https://rt.cpan.org/Ticket/Display.html?id=81860

### CODE REVIEW

**Comment by karenetheridge** [comment]
This commit doesn't give attribution to Zefram, the author.

**Comment by leejo** [comment]
@karenetheridge - For future reference what do i need to do to attribute the commit to the original author, other than including this in the commit message? Changes? POD?

**Comment by karenetheridge** [comment]
`git commit -m"$message" --author="author name <email>" --date="date of patch"`

**Comment by leejo** [comment]
> `--author="author name <email>" --date="date of patch"`

Sorry, not going to take that approach.

**Pull request closed without merging**
